language: java
sudo: true
install: mvn --version
script:
- export MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512m"
- mkdir src/main/resources
- cp configs/analytics.prod.yml src/main/resources/boxfuse.yml
- mvn versions:set -DnewVersion=$BUILD_NUMBER
- mvn versions:commit
- mvn --settings settings.xml clean -DskipITs deploy
after_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=suripu-analytics-$TRAVIS_BRANCH-$BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push --quiet git@github.com:hello/suripu-analytics.git --tags
deploy:
  provider: s3
  access_key_id: $CI_DEPLOY_USERNAME
  secret_access_key: $CI_DEPLOY_PASSWORD
  bucket: hello-deploy
  skip_cleanup: true
  local_dir: configs
  upload-dir: configs/com/hello/analytics/suripu-analytics/$BUILD_NUMBER
  region: us-east-1
  on:
    tags: false
    branch:
    - PRODUCTION
branches:
  only:
  - master
  - PRODUCTION
notifications:
  email:
  - josef+travis-suripu2@sayhello.com
jdk:
- oraclejdk7
env:
  global:
  - BUILD_NUMBER=0.1.$TRAVIS_BUILD_NUMBER
  - secure: DkJvY7MgQRQ8SvHM3NN2aKEFjtrmUQrN5yLwGteERLFA9jtkmesbmokmukIczPvrtxtP4gFBxWz2v/rC7jWhq4+i4Ph0VJiPsM0Yg6RArAGBSQAwkgsWf1yUn6FAGQKCOBWjed49AGo4Yk0QgOUUfEZ8TRM1iLrctUzJmHebohkFyqc4o3eI9Ze7TgZ6lnfYHRAn74oXgqMVWPtRdb4oDtH68Y2YqNanAOPb8ZhaVn0qxV9PamH0AmwfiT/2UsTg80odqUhST32/+oV4LTQBkuXfBiHyfyFt5xTZ0M24d8IPC6422Od26ntbL+2RVy2bxP6zOhJaNxURsLtVYx2Dx1b1nlHANGk1IC4uPMcmUht/HNaTRcXBuiQhoe24eRnMghniv4QfaSOYtIG5LtN+m1ZMjw8NXfXolhUreNAH31U1Dx1Kp6qfEya0kZLX9LVHMS4VzCRF6TW/MpUnYHC1JYj8HeumyRBPsUp8c0GwHibw5yFIjGcrEyeU1JLHm1MmDp+3d5KkgYVyPujrrMAlzyzlk1A0H4cQj/4aSBKPbIAgYK5oWtY8AW/7chw+gNAA90VEI5FJJU4FgoC+6r3wRvQDsUY3dN6rQM89nt+I05mhI5iyPLS2Hy3Vmf6B/mNK8pU3vcyRXZkRsxw5sMGHhAYMoeVkkvxegdO0XCrBC8c=
  - secure: eHhFwmTgquPwslXnqfoJZG/RMihhsADWtsehS0sHgbxeqfmiFpm415ZRUIYQ8juGSCNgnEVCdqLRaSrrCxi6fI6a0iuwkw7yihweZ1MRrR8wlHa8371UuHGL4W3+HZrbK7029CtPR2ILbxs2baZbg1pWBSgZZsRTiVBpLC7+Jet+fnNzeAk6YqnzrVzDSlb7FqagFsgjRW9XBK7GxIrjDd5mSkM2HmQGLvESx+eBDoSDkNbKwdTu/aL7kNw852rvZi9ryD7z9ije1m3iB7Hp0LT7fCsvPDeYomnLBUX+10Mmg4gChsr3ei25YmFhtC89fFCtOCdPQsV752l8Itedo4vbqoAAQjZqn2tWkJUI4z8vtfjtPOdv9PqJB/+h1j4jonNZkn8DGpm163NvybL6nTFnjJhvyD5tOU3mvOUfWOaHPs71fiekzYKLFxGbLEjhI+bbz47BLJxHZqJhePox9jm0yh/DlMiFrFFv+RzOhK+4iT8ZiDsxmtQRdIQgPVhgyUsKZ/UJjWZBF2fafeXUjNNftoBZVnGMnifnZhp9g98+b6o145sFPWyYJ+CFQuM/OkMm/CdFWSepViyOz6qzEsAiLg7gLbqNWdwPDN/l2MFtfTPDxwI+AkMELRZzemZcnLaBdOj3EVTeG9XgUbMsK2wOBQ9cjmuxS2IUDgOJmU4=
  - secure: DXSTaIG8OKYZ7Pgk9pk7BtexrYhuB4oN+DYAQqwLX+nHcjdoIYNiN4y8gQ8lMCBN8IuJMhSI14gIEfJbeFN/8zYfFRtcwsKbDQdEG0o4M0WidgtSsZA9oHYDBu7hRjGXLjJjt65K44YN9YivAl95XXXqL0AJfaX+fg+vxAnYDNRULE5FwOlaJUfdocbu6M4uA9EYuVy6m/xlfYtrZnO/LiczwtBOh9MqK5O7fLwF1EpQq8xf/wlIrk26UlnmvbVa8Z3mIgUfuwErVxuJAKQwfVc6a8XQV3qGA50t3ZN5XzRQ1hUch0gKjYVL+mRAWQKTCgLt4XqQDc/rW98kPUQRCynboG3lfcxkkeszsGcSEmge0dzwuLPec2LYCSBs+Lsm+fjY7UuXODJJqnEtr5WX/U7aF34klCs0gQgncGEOQQllEFioNhEe6+YBPozOpUkH7yug3ZldJc0P+ebw0GAjxHy/n6lIfTIu/cDd0voMK9RoED5u4rK88auvKg8n4iahSzuif5RaVjQ0h1ybaH30m2RmrKQorh5NH9j1VomBk0FJXPA6wvtqiMI0zxP1ixPjEibzZYv2cAkFj1lx0wC4//PNx1Yoi3VX00AeL52rO68AqZlTKLXpSExsIPC+cTs8BXmJ+8Zul5m1rUnhy2Inc7PqRxexjsX+92JdRxZM4Jc=
  - secure: lxRkosvt5b0sv88pGYEjPE7rQtGcBZXri7unJ0Dg0OD0jQt9rCQKoJ2mj93pBOW46MS9st9O/v5Do6vDI0ZJpz65ktfZJay3eg0I8y5P+H0SYx82bRrEVJOgCZWXqoAV5uTw610Or+YpyNzC9B9aZganjMVY0YIPLrmFOjH3C4zNhJOTwnOHFUmdEKDOa1yIiGYhCFLTFOHFDja/gtLxPstMx4/y12Bld9SAFnbThuvckqngp5Avxbxea4hI5l2BXCzzZOc/T8xowol0sdE4wraNfPks7cyqTSeI0GUfh5hKKZwrCETbbp2/JEq/Qq1r4NMygtzJaiJz9vZGF6ggNobdyptGeuyR+zLgUgN2C+yaxMXuy4HKYXfgQdAksNZ9fcUPyGgmpAMSb+6H2rrNW0IjcqDebaaxpUx8gJNKGI4LwRP7tJqskNeXa8PPT9MtHPetb/j0586xC2S2Bh7907z9IQacv1uDvYarkfqiNCQ6pFacvfiB+ZGelhWNzviqXcuxxaSKEJ3g0d/PnYWg+d+tAjH+xrJZPHz0s8FT0Bwj0z9+VioAMoPMVrSr1VFl1WxjAnykGxDZwuWg5T3oHdcnplUBIRrKFVzb124qhrNSHpuOyHE/uFqnRScWbvMZdG8LCYRtH9xpAYtwIFlC05AbwEXqC4oL+sLWPSqvsIE=
