--- 
app_names:
  pill_stats: AnalyticsPillProcessorDev
  sense_stats: AnalyticsSenseProcessorDev
debug: false
kinesis:
  endpoints:
    sense_sensors_data: https://kinesis.us-east-1.amazonaws.com
    batch_pill_data: https://kinesis.us-east-1.amazonaws.com
  streams:
    sense_sensors_data: sense_sensors_data
    batch_pill_data: batch_pill_data

dynamodb:
  region: us-east-1
  tables:
    alarm_info: prod_alarm_info
    sense_last_seen : prod_sense_last_seen
  endpoints:
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen : http://dynamodb.us-east-1.amazonaws.com

logging: 
  level: INFO
  loggers: 
    com.hello.suripu.analytics: INFO

max_records: 1000

metrics_enabled: false

redis: 
  host: stats.xoe7je.0001.use1.cache.amazonaws.com
  port: 6379
