--- 
app_name: AnalyticsProcessorDev
debug: false
kinesis:
  endpoint: https://kinesis.us-east-1.amazonaws.com
  streams:
    sense_sensors_data: sense_sensors_data
dynamodb:
  region: us-east-1
  tables:
    alarm_info: alarm_info
    sense_last_seen : sense_last_seen
  endpoints:
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen : http://localhost:7777

logging: 
  level: INFO
  loggers: 
    com.hello.suripu.analytics: DEBUG
max_records: 1000
metrics_enabled: false
redis: 
  host: localhost
  port: 6379
