--- 
app_names:
  pill_stats: AnalyticsPillProcessor
  sense_stats: AnalyticsSenseProcessor
debug: false
kinesis:
  endpoints:
    sense_sensors_data: https://kinesis.us-east-1.amazonaws.com
    batch_pill_data: https://kinesis.us-east-1.amazonaws.com
  streams:
    sense_sensors_data: sense_sensors_data
    batch_pill_data: batch_pill_data

dynamodb:
  region: us-east-1
  tables:
    alarm_info: prod_alarm_info
    sense_last_seen : prod_sense_last_seen
  endpoints:
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen : http://dynamodb.us-east-1.amazonaws.com

graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.yammer
    - com.hello

logging: 
  level: INFO
  loggers: 
    com.hello.suripu.analytics: INFO

max_records: 1000

metrics_enabled: true

redis: 
  host: stats.xoe7je.0001.use1.cache.amazonaws.com
  port: 6379
