--- 
app_names:
  pill_stats: AnalyticsPillProcessorDev
  sense_stats: AnalyticsSenseProcessorDev
debug: false
kinesis:
  endpoints:
    sense_sensors_data: https://kinesis.us-east-1.amazonaws.com
    batch_pill_data: https://kinesis.us-east-1.amazonaws.com
  streams:
    sense_sensors_data: sense_sensors_data
    batch_pill_data: batch_pill_data

dynamodb:
  region: us-east-1
  tables:
    alarm_info: alarm_info
    sense_last_seen : sense_last_seen
    kinesis_checkpoint_track : kinesis_checkpoint_track
  endpoints:
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen : http://localhost:7777
    kinesis_checkpoint_track : http://localhost:7777

graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.yammer
    - com.hello

logging: 
  level: INFO
  loggers: 
    com.hello.suripu.analytics: DEBUG

max_records: 1000

metrics_enabled: false

redis:
  host: localhost
  port: 6379
