---
server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 2222
      idleTimeout: 25 seconds
  adminConnectors:
    - type: http
      port: 2223
      idleTimeout: 25 seconds

logging:
  level: INFO
  loggers:
    com.hello.suripu: INFO
    com.amazonaws: WARN
  appenders:
    - type: file
      threshold: INFO
      currentLogFilename: /var/log/suripu-analytics/suripu-analytics.log
      archivedLogFilenamePattern: /var/log/suripu-analytics/suripu-analytics-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-analytics
      # timezone: UTC
      # facility: USER
      # sendLocalName: true


app_names:
  pill_stats: AnalyticsPillProcessorProd
  sense_stats: AnalyticsSenseProcessorProd
debug: false
kinesis:
  endpoints:
    sense_sensors_data: https://kinesis.us-east-1.amazonaws.com
    batch_pill_data: https://kinesis.us-east-1.amazonaws.com
  streams:
    sense_sensors_data: sense_sensors_data_fanout_one
    batch_pill_data: batch_pill_data

dynamodb:
  region: us-east-1
  tables:
    kinesis_checkpoint_track : prod_kinesis_checkpoint_track
  endpoints:
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen : http://dynamodb.us-east-1.amazonaws.com
    kinesis_checkpoint_track : http://dynamodb.us-east-1.amazonaws.com

graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - io.dropwizard
    - com.hello

logging: 
  level: INFO
  loggers: 
    com.hello.suripu.analytics: INFO

max_records: 5000

metrics_enabled: true

redis: 
  host: stats.xoe7je.0001.use1.cache.amazonaws.com
  port: 6379
